live_config_reload = true

[colors.bright]
black = "#6D7070"
blue = "#1BA6FA"
cyan = "#73FBF1"
green = "#B8E466"
magenta = "#A578EA"
red = "#FF4352"
white = "#FEFEF8"
yellow = "#FFD750"

[colors.cursor]
cursor = "#FF261E"
text = "#FF261E"

[colors.normal]
black = "#0d0d0d"
blue = "#1BA6FA"
cyan = "#21DEEF"
green = "#A0E521"
magenta = "#8763B8"
red = "#FF301B"
white = "#EBEBEB"
yellow = "#FFC620"

[colors.primary]
background = "#101321"
foreground = "#EBEBEB"

[font]
size = 14.0

[font.normal]
family = "DejaVu Sans Mono for Powerline"

[[hints.enabled]]
command = "open"
post_processing = true
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001F\u007F-<>\"\\s{-}\\^⟨⟩`]+"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

[hints.enabled.mouse]
enabled = true
mods = "None"

[shell]
args = ["--login", "-c", "tmux attach || tmux new -s base; exec zsh"]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_padding = true
dynamic_title = true
